## Metricbeat configuration
## https://github.com/elastic/beats/blob/main/deploy/docker/metricbeat.docker.yml
#

name: metricbeat

metricbeat.config:
  modules:
    path: ${path.config}/modules.d/*.yml
    # Reload module configs as they change:
    reload.enabled: false

metricbeat.autodiscover:
  providers:
    - type: docker
      hints.enabled: true

metricbeat.modules:
- module: elasticsearch
  hosts: ["https://elasticsearch1:9200", "https://elasticsearch2:9200", "https://elasticsearch3:9200"]
  username: monitoring_internal
  password: ${MONITORING_INTERNAL_PASSWORD}
  ssl:
    certificate_authorities: [ /usr/share/metricbeat/ca.crt ]
    verification_mode: certificate
  # xpack.enabled: true
  # period: 60s
  # enabled: true

- module: kibana
  hosts: [ https://kibana:5601 ]
  username: monitoring_internal
  password: ${MONITORING_INTERNAL_PASSWORD}
  ssl:
    certificate_authorities: [ /usr/share/metricbeat/ca.crt ]
    verification_mode: certificate
  # xpack.enabled: true
  # period: 60s
  # enabled: true

- module: logstash
  hosts: ["http://logstash:9600"]
  username: monitoring_internal
  metricsets: ["node", "node_stats"]
  password: ${MONITORING_INTERNAL_PASSWORD}
  ssl:
    certificate_authorities: ["/usr/share/metricbeat/ca.crt"]
    verification_mode: certificate
  # xpack.enabled: true
  # period: 60s
  # enabled: true


# - module: docker
#   metricsets:
#     - container
#     - cpu
#     - diskio
#     - healthcheck
#     - info
#     #- image
#     - memory
#     - network
#   hosts: [ unix:///var/run/docker.sock ]
#   period: 60s
#   enabled: true

- module: system
  period: 60s
  metricsets:
    - cpu
    - load
    - memory
    - network
    - process
    - process_summary
    - socket_summary
    - filesystem
    - fsstat

processors:
  - add_cloud_metadata: ~
  - add_docker_metadata: ~
  - add_kubernetes_metadata: ~

logging.level: info
logging.to_stderr: true

monitoring.enabled: false

output.elasticsearch:
  hosts: ["https://elasticsearch1:9200", "https://elasticsearch2:9200", "https://elasticsearch3:9200"]
  username: metricbeat_internal
  password: ${METRICBEAT_INTERNAL_PASSWORD}
  ssl:
    certificate_authorities: [ /usr/share/metricbeat/ca.crt ]
    verification_mode: certificate

## HTTP endpoint for health checking
## https://www.elastic.co/guide/en/beats/metricbeat/current/http-endpoint.html
#

http:
  enabled: true
  host: 0.0.0.0