services:
  elasticsearch1:
    image: "docker.elastic.co/elasticsearch/elasticsearch:${ELASTIC_VERSION:-9.0.3}"
    volumes:
      - elasticsearch1:/usr/share/elasticsearch/data:Z
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      node.name: elasticsearch1
      cluster.name: docker-cluster
      node.roles: master,data,ingest
      discovery.seed_hosts: elasticsearch2,elasticsearch3
      cluster.initial_master_nodes: elasticsearch1,elasticsearch2,elasticsearch3
      network.host: 0.0.0.0
      network.publish_host: elasticsearch1
      transport.host: 0.0.0.0
      transport.publish_host: elasticsearch1
      transport.publish_port: 9300
      xpack.security.enabled: "true"
      xpack.security.http.ssl.enabled: "true"
      xpack.security.http.ssl.key: /usr/share/elasticsearch/config/elasticsearch.key
      xpack.security.http.ssl.certificate: /usr/share/elasticsearch/config/elasticsearch.crt
      xpack.security.http.ssl.certificate_authorities: /usr/share/elasticsearch/config/ca.crt
      xpack.security.transport.ssl.enabled: "true"
      xpack.security.transport.ssl.verification_mode: certificate
      xpack.security.transport.ssl.key: /usr/share/elasticsearch/config/elasticsearch.key
      xpack.security.transport.ssl.certificate: /usr/share/elasticsearch/config/elasticsearch.crt
      xpack.security.transport.ssl.certificate_authorities: /usr/share/elasticsearch/config/ca.crt
      xpack.license.self_generated.type: basic
      ES_JAVA_OPTS: "-Xms4g -Xmx4g"
      ELASTIC_PASSWORD: "${ELASTIC_PASSWORD:-}"
    secrets:
      - source: elk_ca_crt
        target: /usr/share/elasticsearch/config/ca.crt
      - source: elk_elasticsearch_crt
        target: /usr/share/elasticsearch/config/elasticsearch.crt
      - source: elk_elasticsearch_key
        target: /usr/share/elasticsearch/config/elasticsearch.key
    networks:
      - elk
    deploy:
      replicas: 1
      placement:
        max_replicas_per_node: 1
        constraints:
          - node.labels.elasticsearch1 == true
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 3
        window: 120s

  elasticsearch2:
    image: "docker.elastic.co/elasticsearch/elasticsearch:${ELASTIC_VERSION:-9.0.3}"
    volumes:
      - elasticsearch2:/usr/share/elasticsearch/data:Z
    environment:
      node.name: elasticsearch2
      cluster.name: docker-cluster
      node.roles: master,data,ingest
      discovery.seed_hosts: elasticsearch1,elasticsearch3
      cluster.initial_master_nodes: elasticsearch1,elasticsearch2,elasticsearch3
      network.host: 0.0.0.0
      network.publish_host: elasticsearch2
      transport.host: 0.0.0.0
      transport.publish_host: elasticsearch2
      transport.publish_port: 9300
      xpack.security.enabled: "true"
      xpack.security.http.ssl.enabled: "true"
      xpack.security.http.ssl.key: /usr/share/elasticsearch/config/elasticsearch.key
      xpack.security.http.ssl.certificate: /usr/share/elasticsearch/config/elasticsearch.crt
      xpack.security.http.ssl.certificate_authorities: /usr/share/elasticsearch/config/ca.crt
      xpack.security.transport.ssl.enabled: "true"
      xpack.security.transport.ssl.verification_mode: certificate
      xpack.security.transport.ssl.key: /usr/share/elasticsearch/config/elasticsearch.key
      xpack.security.transport.ssl.certificate: /usr/share/elasticsearch/config/elasticsearch.crt
      xpack.security.transport.ssl.certificate_authorities: /usr/share/elasticsearch/config/ca.crt
      xpack.license.self_generated.type: basic
      ES_JAVA_OPTS: "-Xms4g -Xmx4g"
      ELASTIC_PASSWORD: "${ELASTIC_PASSWORD:-}"
    secrets:
      - source: elk_ca_crt
        target: /usr/share/elasticsearch/config/ca.crt
      - source: elk_elasticsearch_crt
        target: /usr/share/elasticsearch/config/elasticsearch.crt
      - source: elk_elasticsearch_key
        target: /usr/share/elasticsearch/config/elasticsearch.key
    networks:
      - elk
    deploy:
      replicas: 1
      placement:
        max_replicas_per_node: 1
        constraints:
          - node.labels.elasticsearch2 == true
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 3
        window: 120s

  elasticsearch3:
    image: "docker.elastic.co/elasticsearch/elasticsearch:${ELASTIC_VERSION:-9.0.3}"
    volumes:
      - elasticsearch3:/usr/share/elasticsearch/data:Z
    environment:
      node.name: elasticsearch3
      cluster.name: docker-cluster
      node.roles: master,data,ingest
      discovery.seed_hosts: elasticsearch1,elasticsearch2
      cluster.initial_master_nodes: elasticsearch1,elasticsearch2,elasticsearch3
      network.host: 0.0.0.0
      network.publish_host: elasticsearch3
      transport.host: 0.0.0.0
      transport.publish_host: elasticsearch3
      transport.publish_port: 9300
      xpack.security.enabled: "true"
      xpack.security.http.ssl.enabled: "true"
      xpack.security.http.ssl.key: /usr/share/elasticsearch/config/elasticsearch.key
      xpack.security.http.ssl.certificate: /usr/share/elasticsearch/config/elasticsearch.crt
      xpack.security.http.ssl.certificate_authorities: /usr/share/elasticsearch/config/ca.crt
      xpack.security.transport.ssl.enabled: "true"
      xpack.security.transport.ssl.verification_mode: certificate
      xpack.security.transport.ssl.key: /usr/share/elasticsearch/config/elasticsearch.key
      xpack.security.transport.ssl.certificate: /usr/share/elasticsearch/config/elasticsearch.crt
      xpack.security.transport.ssl.certificate_authorities: /usr/share/elasticsearch/config/ca.crt
      xpack.license.self_generated.type: basic
      ES_JAVA_OPTS: "-Xms4g -Xmx4g"
      ELASTIC_PASSWORD: "${ELASTIC_PASSWORD:-}"
    secrets:
      - source: elk_ca_crt
        target: /usr/share/elasticsearch/config/ca.crt
      - source: elk_elasticsearch_crt
        target: /usr/share/elasticsearch/config/elasticsearch.crt
      - source: elk_elasticsearch_key
        target: /usr/share/elasticsearch/config/elasticsearch.key
    networks:
      - elk
    deploy:
      replicas: 1
      placement:
        max_replicas_per_node: 1
        constraints:
          - node.labels.elasticsearch3 == true
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 3
        window: 120s

  kibana:
    image: "docker.elastic.co/kibana/kibana:${ELASTIC_VERSION:-9.0.3}"
    ports:
      - "5601:5601"
    environment:
      KIBANA_SYSTEM_PASSWORD: "${KIBANA_SYSTEM_PASSWORD:-}"
      ELASTICSEARCH_HOSTS: https://elasticsearch1:9200
      ELASTICSEARCH_USERNAME: kibana_system
      ELASTICSEARCH_PASSWORD: "${KIBANA_SYSTEM_PASSWORD:-}"
      ELASTICSEARCH_SSL_CERTIFICATEAUTHORITIES: /usr/share/kibana/config/ca.crt
      SERVER_SSL_ENABLED: "true"
      SERVER_SSL_CERTIFICATE: /usr/share/kibana/config/kibana.crt
      SERVER_SSL_KEY: /usr/share/kibana/config/kibana.key
      SERVER_NAME: kibana
      SERVER_HOST: 0.0.0.0
      TELEMETRY_OPTIN: "false"
      TELEMETRY_ALLOWCHANGINGOPTINSTATUS: "false"
      XPACK_APM_TELEMETRYCOLLECTIONENABLED: "false"
      XPACK_MONITORING_UI_CCS_ENABLED: "false"
      XPACK_ENCRYPTEDSAVEDOBJECTS_ENCRYPTIONKEY: 3827bd200c5241863ed08386da2b40f9
      XPACK_REPORTING_ENCRYPTIONKEY: 78fc59a7ac1348b3d43a161d4c23bef9
      XPACK_SECURITY_ENCRYPTIONKEY: c97e31c7eb741bb2309ca5a5d798a2fc
    secrets:
      - source: elk_ca_crt
        target: /usr/share/kibana/config/ca.crt
      - source: elk_kibana_crt
        target: /usr/share/kibana/config/kibana.crt
      - source: elk_kibana_key
        target: /usr/share/kibana/config/kibana.key
    networks:
      - elk
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      update_config:
        parallelism: 1
        delay: 10s
        order: start-first
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s

networks:
  elk:
    external: true

volumes:
  elasticsearch1:
  elasticsearch2:
  elasticsearch3:

secrets:
  elk_ca_crt:
    external: true
  elk_elasticsearch_crt:
    external: true
  elk_elasticsearch_key:
    external: true
  elk_kibana_crt:
    external: true
  elk_kibana_key:
    external: true