---
## Default Logstash configuration from Logstash base image.
## https://github.com/elastic/logstash/blob/main/docker/data/logstash/config/logstash-full.yml
#
api.http.host: 0.0.0.0

node.name: logstash

xpack.management.enabled: false
xpack.management.elasticsearch.hosts: [ "https://elasticsearch1:9200", "https://elasticsearch2:9200", "https://elasticsearch3:9200" ]
xpack.management.elasticsearch.username: logstash_system
xpack.management.elasticsearch.password: ${LOGSTASH_INTERNAL_PASSWORD}
xpack.management.elasticsearch.ssl.certificate_authority: config/ca.crt
xpack.management.elasticsearch.ssl.verification_mode: certificate

## Logstash pipeline settings
#
path.config: /usr/share/logstash/pipeline.conf
path.logs: /usr/share/logstash/logs